### ISSUE TITLE
Problem at launching Demo/Demo2

### ISSUE THREAD

**Issue by ltorok** [HanSolo/expandabletextarea#2]
Hi.
I try run Demo/Demo2 using this command:
**gradlew.bat run -Dorg.gradle.java.home="C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot" --info**
In Windows CMD console after run command above I get this note:
> Task :run
Caching disabled for task ':run' because:
  Build cache is disabled
Task ':run' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
No module was provided for main class, assuming the current module. Prefer providing 'mainClassName' in the following format: '$moduleName/a.b.Main'

I see problem in:
Task has not declared any outputs despite executing actions.
No module was provided for main class, assuming the current module. Prefer providing 'mainClassName' in the following format: '$moduleName/a.b.Main'

I want ctreate my run.bat for run Demo/Demo2.
Content my run.bat is currently this:
_**"C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot\bin\java.exe" --module-path ../lib;"D:\JavaFX\Gluon\JavaFX Windows SDK\inst\openjfx-11.0.2_windows-x64_bin-sdk\javafx-sdk-11.0.2\lib" --module eu.hansolo.fx.expandabletextarea/eu.hansolo.fx.expandabletextarea.Launcher**_

There is Launcher or Launcher2 to run Demo or Demo2.

But I get this note after launch my run.bat:
Error occurred during initialization of boot layer
java.lang.module.FindException: Module eu.hansolo.fx.expandabletextarea not found

Is there some bug at building? Thanks.

**Comment by HanSolo** [comment]
should be fixed with latest commit

**Comment by ltorok** [comment]
Thanks. It is ok now.
